### ISSUE TITLE
Update to Swift 5

### ISSUE THREAD

**Issue by kimdv** [google/promises#104]
As Swift 5 now is released is there any plan to merge the code to Swift 5?

**Comment by shoumikhin** [comment]
Hi Kim,

Of course! We'll be there sooner or later :)
It all depends on how smooth the upgrade would be, we definitely don't wan't to break anyone.
Feel free to submit a PR with the proposed changes.

Thanks.

**Comment by temrich** [comment]
Hi Kim, we are still looking to update to Swift 5 as soon as possible; however, there's a Bazel [issue](https://github.com/bazelbuild/bazel/pull/7830) with Xcode 10.2 that should be fixed in Bazel 0.25.0. Hoping that once 0.25 is released, we will be able to update to Swift 5. Will continue the discussion in your [PR](https://github.com/google/promises/pull/105). Thank you!
