### ISSUE TITLE
Build failed with Xcode 11.0 beta (11M336w) + Swift 5.1

### ISSUE THREAD

**Issue by MKGitHub** [google/promises#117]
Please fix ASAP!

**Comment by shoumikhin** [comment]
Any more details on what failed exactly?

**Comment by MKGitHub** [comment]
In cases like this it is quite abvious that a new version of Xcode/Swift would break, but any way here is a screenshot. Just download and compile…

<img width="1625" alt=" 2019-06-07 at 10 14 59" src="https://user-images.githubusercontent.com/535550/59090510-4105f380-890d-11e9-88d8-7d06b0522133.png">

**Comment by shoumikhin** [comment]
Thanks!

Looks like this is a duplicate of https://github.com/google/promises/issues/100.
No idea if that was successfully resolved for the user, since we never heard back, but there’s also a temporary workaround. Perhaps, a clean build or SwiftLint update would help. Please, let us know if you manage to find the root cause of the issue.

**Comment by MKGitHub** [comment]
Was using an old version of SwiftLint, after update to latest SwiftInt it works √
