### ISSUE TITLE
Promises vs Facebook Bolts-ObjC

### ISSUE THREAD

**Issue by steipete** [google/promises#18]
First of all, many thanks for releasing promises, it looks extremely useful and I'm happy that we still see a few great Objective-C libraries in 2018.

I notice that you compare it with quite a few other promises libraries, but not with Facebook's [Bolts-ObjC](https://github.com/BoltsFramework/Bolts-ObjC) framework. Since that just came up [on twitter](https://twitter.com/hovox/status/960604311796572160) I'd love to see a comparison/thoughts on how where the main differences are.

If issues are not the right place for these kind of questions, happy to close and post this somewhere else. Thanks!

**Comment by shoumikhin** [comment]
Thanks, Peter!

Actually, the library has been there for a while and we used it internally instead of any other 3rd party solution. Eventually, we've decided to make it public in hope the community would find it useful and contribute with improvements.

Here's the data for Bolts ObjC [performance tests](https://gist.github.com/shoumikhin/50117254c9615e3d4b8efaf68bb9d3b3) you've requested:

|  Test Case | Time in sec |
|------------|-------------|
|testContinueWithBlockOnSerialQueue| 0.00002586 |
|testDoubleContinueWithBlockOnSerialQueue| 0.00003285 |
|testTripleContinueWithBlockOnSerialQueue| 0.00003776 |
|testContinueWithBlockOnConcurrentQueue| 0.02312784 |

And these are the numbers for Promises ObjC [performance tests](https://github.com/google/promises/blob/master/Tests/FBLPromisesPerformanceTests/FBLPromise%2BThenPerformanceTests.m), ran on the same device (iPhone 6s, iOS, 11.2.5):

|  Test Case | Time in sec |
|------------|-------------|
|testThenOnSerialQueue| 0.00002572 |
|testDoubleThenOnSerialQueue| 0.00003398 |
|testTripleThenOnSerialQueue| 0.00003697 |
|testThenOnConcurrentQueue| 0.02318964 |

The results look surprisingly similar. Presumably, because both Bolts and Promises are highly optimized to provide minimum overhead over plain GCD.

Feel free to contribute with other types of tests you'd like to see. Code snippets are highly appreciated.

**Comment by steipete** [comment]
Thanks! We'll look at both and potentially follow up with a post. I appreciate the time!
