### ISSUE TITLE
How to make Promise without returned value?

### ISSUE THREAD

**Issue by alexanderkhitev** [google/promises#37]
Hello! Great framework! Please tell me how to do Promise without a return value? For example, I update the user name in firebase and I expect some value, but only check for an error. I now write Bool as a return value, although in fact I do not need it, how can this be done differently?

I would also like to know what is better to fix in this code for a more productive / readable code using the Promise framework. Thanks.

Sample code 

```
    private func updateName(_ name: String) -> Promise<Bool> {
        let promise = Promise<Bool>(on: .global(qos: .default)) { fulfill, reject in
            guard let userID = UserRealmManager().getUser()?.id else {
                // TODO: - make custom error
                return
            }
            let ref = Database.database().reference().child(UsersPaths.Main.users.rawValue).child(userID)
            let data = [UsersPaths.UserProperties.displayName.rawValue : userID]
            ref.updateChildValues(data, withCompletionBlock: { (error, _) in
                if let error = error {
                    reject(error)
                } else {
                    fulfill(true)
                }
            })
        }
        return promise
    }

```

**Comment by shoumikhin** [comment]
Hi Alex,

I imagine [`resolve`](https://github.com/google/promises/blob/master/g3doc/index.md#resolve) could work for you?

```swift
private func updateName(_ name: String) -> Promise<Type> {
  return resolve { handler in
    guard let userID = UserRealmManager().getUser()?.id else { throw CustomError }
    let ref = Database.database().reference().child(UsersPaths.Main.users.rawValue).child(userID)
    ref.updateChildValues([UsersPaths.UserProperties.displayName.rawValue : userID], handler)
  }
}
```

Where the `Type` of the promise would be the same as whatever the type of `updateChildValues` completion handler is. You may also need to specify the type of `handler` for `resolve` operator explicitly as `(handler: @escaping (Type?, Error?) -> Void)` to disambiguate between other `resolve` overloads.

If you'd like to use `Void` instead of that `Type`, you can chain another `then` at the end, like so:

```swift
return resolve { handler in
  //...
}.then { _ in () }
```
Where `()` constructs and returns an empty tuple, i.e. the value of type `Void`.

Also, notice that `resolve` by default is invoked on the main dispatch queue. In your example you've used a background queue. Is that important? Which piece of that code must use a background queue instead?

**Comment by richardtop** [comment]
Hi @alexanderkhitev and @shoumikhin, I use `Void` type for such cases:

`Promise<Void>` - it works great for cases, when you only need to check for the result:

```Swift
  @discardableResult func logOut() -> Promise<Void> {
// Clear local storage
    return client.request(EXPIRE_TOKEN_API_ENDPOINT)
  }


// Somewhere in code

loginService.logOut()

or:
loginService.logOut().then .....
```

**Comment by shoumikhin** [comment]
Hi @alexanderkhitev, 

I've updated the answer above. Since [`1.1.0`](https://github.com/google/promises/releases/tag/1.1.0) you can pass an arbitrary dispatch queue to the `wrap` operator (former `resolve`) to achieve the behavior you wanted. Let us know if still have any issues, we're happy to help.

Thanks.
